// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mon_sms_pro/models/campaign/campaign_count_model.dart';
import 'package:mon_sms_pro/models/campaign/campaign_model.dart';
import 'package:mon_sms_pro/models/campaign/campaign_recurring_day_model.dart';
import 'package:mon_sms_pro/models/contact/contact_model.dart';
import 'package:mon_sms_pro/models/core/import_model.dart';
import 'package:mon_sms_pro/models/core/offer_model.dart';
import 'package:mon_sms_pro/models/core/otp_model.dart';
import 'package:mon_sms_pro/models/core/user_model.dart';
import 'package:mon_sms_pro/models/core/version_model.dart';
import 'package:mon_sms_pro/models/group/group_contact_list_model.dart';
import 'package:mon_sms_pro/models/group/group_count_model.dart';
import 'package:mon_sms_pro/models/group/group_model.dart';
import 'package:mon_sms_pro/models/lerezo/company_followed_model.dart';
import 'package:mon_sms_pro/models/lerezo/company_type_model.dart';
import 'package:mon_sms_pro/models/lerezo/follower_model.dart';
import 'package:mon_sms_pro/models/sender/sender_model.dart';
import 'package:mon_sms_pro/models/template/template_model.dart';
import 'package:mon_sms_pro/models/transaction/transaction_model.dart';
import 'package:mon_sms_pro/models/utils.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignCountModelAdapter());
    registerAdapter(CampaignModelAdapter());
    registerAdapter(CampaignRecurringDayModelAdapter());
    registerAdapter(CompanyFollowedModelAdapter());
    registerAdapter(CompanyTypeModelAdapter());
    registerAdapter(ContactModelAdapter());
    registerAdapter(CoordsAdapter());
    registerAdapter(CountryAdapter());
    registerAdapter(FollowerModelAdapter());
    registerAdapter(GroupContactListModelAdapter());
    registerAdapter(GroupCountModelAdapter());
    registerAdapter(GroupModelAdapter());
    registerAdapter(ImportModelAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(OTPModelAdapter());
    registerAdapter(OTPStatusAdapter());
    registerAdapter(OfferModelAdapter());
    registerAdapter(OfferNameAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(SMSTypeAdapter());
    registerAdapter(SenderModelAdapter());
    registerAdapter(SenderStatusAdapter());
    registerAdapter(SexTypeAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VersionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignCountModelAdapter());
    registerAdapter(CampaignModelAdapter());
    registerAdapter(CampaignRecurringDayModelAdapter());
    registerAdapter(CompanyFollowedModelAdapter());
    registerAdapter(CompanyTypeModelAdapter());
    registerAdapter(ContactModelAdapter());
    registerAdapter(CoordsAdapter());
    registerAdapter(CountryAdapter());
    registerAdapter(FollowerModelAdapter());
    registerAdapter(GroupContactListModelAdapter());
    registerAdapter(GroupCountModelAdapter());
    registerAdapter(GroupModelAdapter());
    registerAdapter(ImportModelAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(OTPModelAdapter());
    registerAdapter(OTPStatusAdapter());
    registerAdapter(OfferModelAdapter());
    registerAdapter(OfferNameAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(SMSTypeAdapter());
    registerAdapter(SenderModelAdapter());
    registerAdapter(SenderStatusAdapter());
    registerAdapter(SexTypeAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VersionModelAdapter());
  }
}
