// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mon_sms_pro/models/campaign/campaign_model.dart';
import 'package:mon_sms_pro/models/campaign/campaign_recurring_day_model.dart';
import 'package:mon_sms_pro/models/company_followed_model.dart';
import 'package:mon_sms_pro/models/company_type_model.dart';
import 'package:mon_sms_pro/models/contact_model.dart';
import 'package:mon_sms_pro/models/follower_model.dart';
import 'package:mon_sms_pro/models/import_model.dart';
import 'package:mon_sms_pro/models/offer_model.dart';
import 'package:mon_sms_pro/models/otp_model.dart';
import 'package:mon_sms_pro/models/sender_model.dart';
import 'package:mon_sms_pro/models/template_model.dart';
import 'package:mon_sms_pro/models/transaction_model.dart';
import 'package:mon_sms_pro/models/user_model.dart';
import 'package:mon_sms_pro/models/version_model.dart';
import 'package:mon_sms_pro/utils.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignModelAdapter());
    registerAdapter(CampaignRecurringDayModelAdapter());
    registerAdapter(CompanyFollowedModelAdapter());
    registerAdapter(CompanyTypeModelAdapter());
    registerAdapter(ContactModelAdapter());
    registerAdapter(CoordsAdapter());
    registerAdapter(CountryAdapter());
    registerAdapter(FollowerModelAdapter());
    registerAdapter(ImportModelAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(OTPModelAdapter());
    registerAdapter(OTPStatusAdapter());
    registerAdapter(OfferModelAdapter());
    registerAdapter(OfferNameAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(SMSTypeAdapter());
    registerAdapter(SenderModelAdapter());
    registerAdapter(SenderStatusAdapter());
    registerAdapter(SexTypeAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VersionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CampaignModelAdapter());
    registerAdapter(CampaignRecurringDayModelAdapter());
    registerAdapter(CompanyFollowedModelAdapter());
    registerAdapter(CompanyTypeModelAdapter());
    registerAdapter(ContactModelAdapter());
    registerAdapter(CoordsAdapter());
    registerAdapter(CountryAdapter());
    registerAdapter(FollowerModelAdapter());
    registerAdapter(ImportModelAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(OTPModelAdapter());
    registerAdapter(OTPStatusAdapter());
    registerAdapter(OfferModelAdapter());
    registerAdapter(OfferNameAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(SMSTypeAdapter());
    registerAdapter(SenderModelAdapter());
    registerAdapter(SenderStatusAdapter());
    registerAdapter(SexTypeAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionStatusAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VersionModelAdapter());
  }
}
